#!/usr/bin/env npx tsx
/**
 * BSOP — Supabase functions reference generator (blindaje-financiero S1)
 *
 * Regenera `supabase/FUNCTIONS_REF.md` con la definición VIVA
 * (`pg_get_functiondef`) de todas las funciones/procedures de los schemas de
 * negocio, más triggers y CHECK constraints por tabla. Es la fuente canónica
 * de la que debe partir TODA redefinición de una función en una migración —
 * nunca de la migración anterior (clase del incidente FIFO: una migración
 * partió de una versión vieja del RPC y reintrodujo un bug por 11 días).
 *
 * Hermano de `gen-schema-ref.ts` y validado por el mismo modelo shadow-DB
 * (`schema-check.yml`): las migraciones son la fuente de verdad; si la
 * definición que producen difiere de la commiteada, CI falla y el diff del PR
 * muestra exactamente qué cambió en el cuerpo de la función.
 *
 * Uso:
 *   SUPABASE_DB_URL=postgres://... npm run functions:ref
 *   SUPABASE_DB_URL=postgres://... npm run functions:check
 *
 * Flags:
 *   --schemas core,erp      Limita los schemas (default: paridad con schema:ref).
 *   --out supabase/F.md     Ruta de salida (default: supabase/FUNCTIONS_REF.md).
 *   --dry-run               Escribe a stdout en lugar del archivo.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { Client } from 'pg';

import { loadEnvLocal } from './lib/env-local';

// ── CLI flags ─────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');

function flagValue(flag: string, fallback: string): string {
  const i = args.indexOf(flag);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}

const SCHEMAS = flagValue(
  '--schemas',
  'public,core,erp,rdb,playtomic,health,dilesa,maquinaria,analytics,peptides,sanren'
)
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);

const OUT_PATH = path.resolve(process.cwd(), flagValue('--out', 'supabase/FUNCTIONS_REF.md'));

// ── Types ─────────────────────────────────────────────────────────────────────

export interface FunctionRow {
  schema: string;
  name: string;
  /** `pg_get_function_identity_arguments` — distingue overloads. */
  identityArgs: string;
  kind: 'function' | 'procedure';
  /** `pg_get_functiondef` — el cuerpo completo CREATE OR REPLACE. */
  definition: string;
  comment: string | null;
}

export interface TriggerRow {
  schema: string;
  table: string;
  name: string;
  /** `pg_get_triggerdef` — una línea. */
  definition: string;
}

export interface CheckRow {
  schema: string;
  table: string;
  name: string;
  /** `pg_get_constraintdef` — una línea. */
  definition: string;
}

export interface FunctionsData {
  functions: FunctionRow[];
  triggers: TriggerRow[];
  checks: CheckRow[];
}

// ── Pure formatter (exported for tests) ───────────────────────────────────────

export interface FormatOptions {
  schemas: string[];
  generatedAt: string;
}

/**
 * Formatea `FunctionsData` como markdown determinístico.
 *
 * Contrato:
 * - Schemas en orden alfabético de `opts.schemas`.
 * - Funciones por nombre y luego por identity args (overloads estables).
 * - Triggers y CHECKs agrupados por tabla, alfabético.
 * - Cada definición de función en un fence ```sql``` (diffs legibles en PRs).
 */
export function formatFunctionsRef(data: FunctionsData, opts: FormatOptions): string {
  const sortedSchemas = [...opts.schemas].sort();

  const fnsBySchema = new Map<string, FunctionRow[]>();
  for (const f of data.functions) {
    const arr = fnsBySchema.get(f.schema) ?? [];
    arr.push(f);
    fnsBySchema.set(f.schema, arr);
  }
  for (const arr of fnsBySchema.values()) {
    arr.sort(
      (a, b) => a.name.localeCompare(b.name) || a.identityArgs.localeCompare(b.identityArgs)
    );
  }

  const trgBySchema = new Map<string, TriggerRow[]>();
  for (const t of data.triggers) {
    const arr = trgBySchema.get(t.schema) ?? [];
    arr.push(t);
    trgBySchema.set(t.schema, arr);
  }
  for (const arr of trgBySchema.values()) {
    arr.sort((a, b) => a.table.localeCompare(b.table) || a.name.localeCompare(b.name));
  }

  const chkBySchema = new Map<string, CheckRow[]>();
  for (const c of data.checks) {
    const arr = chkBySchema.get(c.schema) ?? [];
    arr.push(c);
    chkBySchema.set(c.schema, arr);
  }
  for (const arr of chkBySchema.values()) {
    arr.sort((a, b) => a.table.localeCompare(b.table) || a.name.localeCompare(b.name));
  }

  const lines: string[] = [];
  lines.push('# BSOP Supabase Functions Reference');
  lines.push('');
  lines.push('<!--');
  lines.push('  Auto-generated by `scripts/gen-functions-ref.ts`.');
  lines.push(`  Last regenerated: ${opts.generatedAt}`);
  lines.push(`  Schemas: ${sortedSchemas.join(', ')}`);
  lines.push('  DO NOT EDIT BY HAND.');
  lines.push('  Regenerate via: `npm run functions:ref` (requires SUPABASE_DB_URL).');
  lines.push('-->');
  lines.push('');
  lines.push(
    'Fuente canónica de la definición viva de las funciones, triggers y CHECK ' +
      'constraints de BSOP, tal como las producen las migraciones (shadow DB). ' +
      '**Toda redefinición de una función en una migración nueva debe partir del ' +
      'cuerpo que aparece aquí** — nunca de la migración anterior (esa clase de ' +
      'error causó el incidente FIFO de CxC). CI valida este archivo contra la ' +
      'shadow en `schema-check.yml`.'
  );
  lines.push('');
  lines.push(`**Schemas cubiertos:** ${sortedSchemas.map((s) => `\`${s}\``).join(' · ')}`);
  lines.push('');

  for (const schema of sortedSchemas) {
    lines.push('---');
    lines.push('');
    lines.push(`## Schema \`${schema}\``);
    lines.push('');

    const fns = fnsBySchema.get(schema) ?? [];
    const trgs = trgBySchema.get(schema) ?? [];
    const chks = chkBySchema.get(schema) ?? [];

    if (fns.length === 0 && trgs.length === 0 && chks.length === 0) {
      lines.push('_(sin funciones, triggers ni CHECK constraints)_');
      lines.push('');
      continue;
    }

    if (fns.length > 0) {
      lines.push(`### Funciones (${fns.length})`);
      lines.push('');
      for (const f of fns) {
        const kindLabel = f.kind === 'procedure' ? ' _(procedure)_' : '';
        lines.push(`#### \`${f.schema}.${f.name}(${f.identityArgs})\`${kindLabel}`);
        lines.push('');
        if (f.comment) {
          for (const ln of f.comment.split(/\r?\n/)) {
            lines.push(`> ${ln}`);
          }
          lines.push('');
        }
        lines.push('```sql');
        // Normalizar CRLF y trailing whitespace por línea para diffs estables.
        for (const ln of f.definition.replace(/\r\n/g, '\n').split('\n')) {
          lines.push(ln.replace(/[ \t]+$/, ''));
        }
        lines.push('```');
        lines.push('');
      }
    }

    if (trgs.length > 0) {
      lines.push(`### Triggers (${trgs.length})`);
      lines.push('');
      let currentTable = '';
      for (const t of trgs) {
        if (t.table !== currentTable) {
          currentTable = t.table;
          lines.push(`**\`${t.schema}.${t.table}\`**`);
          lines.push('');
        }
        lines.push(`- \`${t.name}\`: \`${t.definition}\``);
      }
      lines.push('');
    }

    if (chks.length > 0) {
      lines.push(`### CHECK constraints (${chks.length})`);
      lines.push('');
      let currentTable = '';
      for (const c of chks) {
        if (c.table !== currentTable) {
          currentTable = c.table;
          lines.push(`**\`${c.schema}.${c.table}\`**`);
          lines.push('');
        }
        lines.push(`- \`${c.name}\`: \`${c.definition}\``);
      }
      lines.push('');
    }
  }

  return lines.join('\n').replace(/\n+$/, '') + '\n';
}

// ── Postgres fetch layer ──────────────────────────────────────────────────────

async function fetchFunctionsData(client: Client, schemas: string[]): Promise<FunctionsData> {
  // Funciones y procedures propios (excluye miembros de extensiones vía
  // pg_depend deptype='e' — pg_trgm, pgcrypto y demás se instalan en schemas
  // cubiertos y no son nuestros). prokind: 'f' function, 'p' procedure —
  // aggregates/window ('a'/'w') no soportan pg_get_functiondef.
  const fnsRes = await client.query<{
    schema: string;
    name: string;
    identity_args: string;
    prokind: 'f' | 'p';
    definition: string;
    comment: string | null;
  }>(
    `
    SELECT
      n.nspname AS schema,
      p.proname AS name,
      pg_get_function_identity_arguments(p.oid) AS identity_args,
      p.prokind AS prokind,
      pg_get_functiondef(p.oid) AS definition,
      obj_description(p.oid, 'pg_proc') AS comment
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = ANY($1::text[])
      AND p.prokind IN ('f', 'p')
      AND NOT EXISTS (
        SELECT 1 FROM pg_depend d
        WHERE d.classid = 'pg_proc'::regclass
          AND d.objid = p.oid
          AND d.deptype = 'e'
      )
    ORDER BY n.nspname, p.proname, identity_args
    `,
    [schemas]
  );

  const functions: FunctionRow[] = fnsRes.rows.map((r) => ({
    schema: r.schema,
    name: r.name,
    identityArgs: r.identity_args,
    kind: r.prokind === 'p' ? 'procedure' : 'function',
    definition: r.definition,
    comment: r.comment,
  }));

  // Triggers de usuario (tgisinternal excluye los de FKs/constraints).
  const trgRes = await client.query<{
    schema: string;
    table: string;
    name: string;
    definition: string;
  }>(
    `
    SELECT
      n.nspname AS schema,
      c.relname AS "table",
      t.tgname  AS name,
      pg_get_triggerdef(t.oid) AS definition
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = ANY($1::text[])
      AND NOT t.tgisinternal
    ORDER BY n.nspname, c.relname, t.tgname
    `,
    [schemas]
  );

  const triggers: TriggerRow[] = trgRes.rows.map((r) => ({
    schema: r.schema,
    table: r.table,
    name: r.name,
    definition: r.definition,
  }));

  // CHECK constraints (contype='c').
  const chkRes = await client.query<{
    schema: string;
    table: string;
    name: string;
    definition: string;
  }>(
    `
    SELECT
      n.nspname   AS schema,
      c.relname   AS "table",
      con.conname AS name,
      pg_get_constraintdef(con.oid) AS definition
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = ANY($1::text[])
      AND con.contype = 'c'
    ORDER BY n.nspname, c.relname, con.conname
    `,
    [schemas]
  );

  const checks: CheckRow[] = chkRes.rows.map((r) => ({
    schema: r.schema,
    table: r.table,
    name: r.name,
    definition: r.definition,
  }));

  return { functions, triggers, checks };
}

// ── CLI entry ─────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  loadEnvLocal();
  const connectionString = process.env.SUPABASE_DB_URL;
  if (!connectionString) {
    console.error(
      '✖ SUPABASE_DB_URL no está definida.\n' +
        '  Para regenerar desde la shadow local: supabase start && npm run db:regen.\n' +
        '  Ejemplo: SUPABASE_DB_URL=postgres://... npm run functions:ref'
    );
    process.exit(1);
  }

  const client = new Client({ connectionString });
  await client.connect();
  let output: string;
  try {
    const data = await fetchFunctionsData(client, SCHEMAS);
    output = formatFunctionsRef(data, {
      schemas: SCHEMAS,
      generatedAt: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
    });
  } finally {
    await client.end();
  }

  if (DRY_RUN) {
    process.stdout.write(output);
    return;
  }

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, output, 'utf8');
  console.log(
    `✔ Escrito ${path.relative(process.cwd(), OUT_PATH)} (${output.length.toLocaleString()} bytes, schemas: ${SCHEMAS.join(', ')})`
  );
}

// Ejecutar solo cuando se invoca directamente (no al importar desde tests).
const isMainModule = (() => {
  try {
    const invoked = process.argv[1] ? path.resolve(process.argv[1]) : '';
    const here = path.resolve(__filename);
    return invoked === here;
  } catch {
    return false;
  }
})();

if (isMainModule) {
  main().catch((err) => {
    console.error('✖ Error al regenerar FUNCTIONS_REF.md:', err);
    process.exit(1);
  });
}
